### ISSUE TITLE
Section labels need to be visible for initial spawn

### ISSUE THREAD

**Issue by leetleyang** [hanjinliu/ChimeraX-command-palette#1]
This is brilliant!

Experiencing a small bug. If section labels aren't enabled, spawning the palette brings up an error:

```
UnboundLocalError: cannot access local variable 'label' where it is not associated with a value.

File "/Users/<redacted>/Library/Application Support/ChimeraX/1.7/lib/python/site-packages/chimerax/command_palette/core.py", line 110, in iter_toolbar_actions
yield action, [tab_name, label, text]
^^^^^^^^
```

Once spawned, section labels can be hidden without affecting usage.

ChimeraX 1.7.1 running on macOS 14.4.1 (arm64)

**Comment by hanjinliu** [comment]
Hi @leetleyang ,
thank you for the bug report! I didn't know the section labels can be hidden ... 😓 
I think now it's fixed.
